import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './navbar'
import Header from './header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen flex-col text-slate-950 bg-slate-50`}>
        <Header />
        <main className='grow grid sm:grid-cols-[1fr_4fr]'>
          <div className='hidden sm:grid'>
            <Navbar />
          </div>
          {children}
        </main>
      </body>
    </html>
  )
}
